- op: add
  path: /spec/template/spec/containers/0/envFrom/1
  value:
    secretRef:
      name: mysql-secret

- op: add
  path: /spec/template/spec/containers/0/volumeMounts
  value:
    - name: secrets
      mountPath: /var/secrets
- op: add
  path: /spec/template/spec/volumes
  value:
    - name: secrets
      secret:
        defaultMode: 420
        secretName: mysql-secret