apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/app/
namespace: mysql
namePrefix: mysql-
replicas:
  - name: deployment
    count: 1
commonLabels:
  app: mysql
resources:
  - sealed-secret.yaml
images:
  - name: docker-repository
    newName: gcr.io/docker-repo/mysql
    newTag: 'develop-z9377412d50210d483ca6a533faf781a8af'
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: deployment
    path: deployment-patch.yaml